server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  web:
    resources:
      static-locations[1]: classpath:/static/
      static-locations[0]: file:src/main/resources/static/
  jpa:
    database: MYSQL
    show-sql: true
    propertes:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/chc
    username: root
    password: codeacademy
    driverClassName: com.mysql.jdbc.Driver
